/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import java.sql.SQLException;

import dados.*;
import exceptions.*;
import java.io.FileNotFoundException;
import java.util.Objects;

import javax.swing.DefaultComboBoxModel;
import negocio.Sistema;
/* criar uma classe só pra tabela;

getColumnCount(){return colunas.lenght()}
getValueAt



*/

/**
 * 
 *
 * @author gustavo
 */
public class notasUDESCfinalUI extends javax.swing.JFrame {
    static Sistema sistema;

    /**
     * Creates new form notasUDESCfinalUI
     */
    public notasUDESCfinalUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JFrame();
        camposenha = new javax.swing.JPasswordField();
        campocpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        darLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        TelaCadastro = new javax.swing.JFrame();
        cpf = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        titCadastro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cpf1 = new javax.swing.JTextField();
        errologin = new javax.swing.JDialog();
        okerro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        TelaPrincipal = new javax.swing.JFrame();
        CadastrarSemestre = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jTextField6 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        cadastSemes = new javax.swing.JFrame();
        nomeSemestre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ErroCadastro = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cadastDis = new javax.swing.JFrame();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cadastAva = new javax.swing.JFrame();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editaSem = new javax.swing.JFrame();
        nomeSemestre2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        editaDis = new javax.swing.JFrame();
        nomeDisciplina3 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        editaAva = new javax.swing.JFrame();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        cadastro = new javax.swing.JButton();
        Inicio = new javax.swing.JLabel();

        TelaLogin.setFocusTraversalPolicyProvider(true);
        TelaLogin.setSize(new java.awt.Dimension(251, 278));

        camposenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposenhaActionPerformed(evt);
            }
        });

        campocpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocpfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Login");

        darLogin.setText("login");
        darLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darLoginActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("cpf");

        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("senha");

        jButton20.setText("voltar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin.getContentPane());
        TelaLogin.getContentPane().setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLoginLayout.createSequentialGroup()
                .addGroup(TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaLoginLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(campocpf)
                            .addComponent(jLabel6)
                            .addComponent(camposenha, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                    .addGroup(TelaLoginLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(TelaLoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(darLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camposenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(darLogin))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        TelaCadastro.setSize(new java.awt.Dimension(260, 390));

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });

        cadastrar.setText("cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        titCadastro.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        titCadastro.setText("Cadastro");

        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("cpf");

        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("nome");

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("senha");

        jButton19.setText("voltar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("curso");

        cpf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaCadastroLayout = new javax.swing.GroupLayout(TelaCadastro.getContentPane());
        TelaCadastro.getContentPane().setLayout(TelaCadastroLayout);
        TelaCadastroLayout.setHorizontalGroup(
            TelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(cadastrar)
                .addGap(17, 17, 17))
            .addGroup(TelaCadastroLayout.createSequentialGroup()
                .addGroup(TelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaCadastroLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(titCadastro))
                    .addGroup(TelaCadastroLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(TelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(cpf)
                            .addComponent(nome)
                            .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(cpf1))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        TelaCadastroLayout.setVerticalGroup(
            TelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titCadastro)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(5, 5, 5)
                .addComponent(cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(TelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(jButton19))
                .addGap(33, 33, 33))
        );

        errologin.setSize(new java.awt.Dimension(299, 137));

        okerro.setText("Voltar pra tela de login");
        okerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okerroActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("USUARIO NAO ENCONTRADO");

        javax.swing.GroupLayout errologinLayout = new javax.swing.GroupLayout(errologin.getContentPane());
        errologin.getContentPane().setLayout(errologinLayout);
        errologinLayout.setHorizontalGroup(
            errologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errologinLayout.createSequentialGroup()
                .addGroup(errologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(errologinLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(okerro))
                    .addGroup(errologinLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel7)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        errologinLayout.setVerticalGroup(
            errologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errologinLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okerro)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jTextPane1);

        TelaPrincipal.setSize(new java.awt.Dimension(518, 553));

        CadastrarSemestre.setText("cadastrar Semestre");
        CadastrarSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarSemestreActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar Disciplina");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("Cadastrar avaliacao");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Remover semestre");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextPane2.setBorder(new javax.swing.border.MatteBorder(null));
        jTextPane2.setText("A avaliacao aparecera aqui depois de selecionada");
        jTextPane2.setToolTipText("");
        jTextPane2.setMinimumSize(new java.awt.Dimension(130, 130));
        jScrollPane7.setViewportView(jTextPane2);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton11.setText("adicionar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTextPane3.setText("A situacao do exame aparecera aqui depois de selecionada a disciplina com avaliacoes cadastradas");
        jScrollPane8.setViewportView(jTextPane3);

        jButton13.setText("Gerar pdf");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Remover disciplina");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Sair");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o semestre" }));
        jComboBox1.setToolTipText("Selecione o semestre");
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a disciplina" }));
        jComboBox3.setToolTipText("Selecione o semestre");
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a avaliacao" }));
        jComboBox4.setToolTipText("Selecione o semestre");
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover avaliacao");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Editar semestre");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("nota");

        jButton12.setText("Editar disciplina");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton17.setText("Editar avaliacao");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaPrincipalLayout = new javax.swing.GroupLayout(TelaPrincipal.getContentPane());
        TelaPrincipal.getContentPane().setLayout(TelaPrincipalLayout);
        TelaPrincipalLayout.setHorizontalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CadastrarSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton15)))
                .addGap(31, 31, 31))
        );
        TelaPrincipalLayout.setVerticalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(CadastrarSemestre)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton4))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addGap(47, 47, 47)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton15))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("Selecione o semestre");

        cadastSemes.setSize(new java.awt.Dimension(279, 164));

        nomeSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeSemestreActionPerformed(evt);
            }
        });

        jButton1.setText("cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("periodo letivo");

        javax.swing.GroupLayout cadastSemesLayout = new javax.swing.GroupLayout(cadastSemes.getContentPane());
        cadastSemes.getContentPane().setLayout(cadastSemesLayout);
        cadastSemesLayout.setHorizontalGroup(
            cadastSemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastSemesLayout.createSequentialGroup()
                .addGroup(cadastSemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastSemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nomeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cadastSemesLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel10)
                            .addGap(111, 111, 111)))
                    .addGroup(cadastSemesLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        cadastSemesLayout.setVerticalGroup(
            cadastSemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastSemesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        ErroCadastro.setSize(new java.awt.Dimension(319, 140));

        jButton2.setText("Voltar à tela de cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("USUARIO JA CADASTRADO");

        javax.swing.GroupLayout ErroCadastroLayout = new javax.swing.GroupLayout(ErroCadastro.getContentPane());
        ErroCadastro.getContentPane().setLayout(ErroCadastroLayout);
        ErroCadastroLayout.setHorizontalGroup(
            ErroCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErroCadastroLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(ErroCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addGap(65, 65, 65))
        );
        ErroCadastroLayout.setVerticalGroup(
            ErroCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErroCadastroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        cadastDis.setSize(new java.awt.Dimension(261, 149));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton5.setText("cadastrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("disciplina");

        javax.swing.GroupLayout cadastDisLayout = new javax.swing.GroupLayout(cadastDis.getContentPane());
        cadastDis.getContentPane().setLayout(cadastDisLayout);
        cadastDisLayout.setHorizontalGroup(
            cadastDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastDisLayout.createSequentialGroup()
                .addGroup(cadastDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastDisLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(cadastDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cadastDisLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton5)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        cadastDisLayout.setVerticalGroup(
            cadastDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastDisLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        cadastAva.setSize(new java.awt.Dimension(226, 249));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton9.setText("cadastrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("nome");

        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("peso");

        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("data");

        javax.swing.GroupLayout cadastAvaLayout = new javax.swing.GroupLayout(cadastAva.getContentPane());
        cadastAva.getContentPane().setLayout(cadastAvaLayout);
        cadastAvaLayout.setHorizontalGroup(
            cadastAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastAvaLayout.createSequentialGroup()
                .addGroup(cadastAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastAvaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(cadastAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)))
                    .addGroup(cadastAvaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton9)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        cadastAvaLayout.setVerticalGroup(
            cadastAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastAvaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        editaSem.setSize(new java.awt.Dimension(270, 146));

        nomeSemestre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeSemestre2ActionPerformed(evt);
            }
        });

        jButton6.setText("atualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("periodo letivo");

        javax.swing.GroupLayout editaSemLayout = new javax.swing.GroupLayout(editaSem.getContentPane());
        editaSem.getContentPane().setLayout(editaSemLayout);
        editaSemLayout.setHorizontalGroup(
            editaSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaSemLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(editaSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(nomeSemestre2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editaSemLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton6)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        editaSemLayout.setVerticalGroup(
            editaSemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaSemLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeSemestre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        editaDis.setSize(new java.awt.Dimension(270, 152));

        nomeDisciplina3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplina3ActionPerformed(evt);
            }
        });

        jButton16.setText("atualizar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("disciplina");

        javax.swing.GroupLayout editaDisLayout = new javax.swing.GroupLayout(editaDis.getContentPane());
        editaDis.getContentPane().setLayout(editaDisLayout);
        editaDisLayout.setHorizontalGroup(
            editaDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaDisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(editaDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(nomeDisciplina3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editaDisLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton16)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        editaDisLayout.setVerticalGroup(
            editaDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaDisLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeDisciplina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton16)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        editaAva.setSize(new java.awt.Dimension(226, 249));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jButton18.setText("atualizar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("nome");

        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("peso");

        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("data");

        javax.swing.GroupLayout editaAvaLayout = new javax.swing.GroupLayout(editaAva.getContentPane());
        editaAva.getContentPane().setLayout(editaAvaLayout);
        editaAvaLayout.setHorizontalGroup(
            editaAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaAvaLayout.createSequentialGroup()
                .addGroup(editaAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editaAvaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(editaAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9)))
                    .addGroup(editaAvaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton18)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        editaAvaLayout.setVerticalGroup(
            editaAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaAvaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(5, 5, 5)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setBackground(new java.awt.Color(153, 255, 51));
        setFont(new java.awt.Font("Bitstream Vera Sans", 0, 10)); // NOI18N
        setSize(new java.awt.Dimension(208, 183));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        login.setText("Login");
        login.setToolTipText("");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        cadastro.setText("Cadastro");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        Inicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Inicio.setText("Inicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Inicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastro)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaPrincipal.setVisible(false);
       cadastDis.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Disciplina dis = new Disciplina();
        dis.setNome(jTextField2.getText());
        dis.setId_semestre(sistema.getIdSemestre());
        try {
            sistema.cadastrarDisciplina(dis);
            jComboBox3.setModel(new DefaultComboBoxModel());      
            jComboBox3.addItem("Selecione a disciplina");
            for (int i = 0; i < sistema.mostraDisciplinas().size(); i++) {
                jComboBox3.addItem(sistema.mostraDisciplinas().get(i).getNome());
                
        cadastDis.setVisible(false);
        TelaPrincipal.setVisible(true); // hides it temporarily
            }
        } catch (InsertException | SelectException e) {
            
        }

        }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                                  
       TelaPrincipal.setVisible(false);
       cadastAva.setVisible(true); }// TODO add your handling code here:    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Avaliacao ava = new Avaliacao();
        ava.setNome(jTextField3.getText());
        ava.setData(jTextField4.getText());
        ava.setPeso(Double.parseDouble(jTextField5.getText()));

        ava.setId_disciplina(sistema.getIdDisciplina());
        try {
            sistema.cadastrarAvaliacao(ava);
            jComboBox4.setModel(new DefaultComboBoxModel());      
            jComboBox4.addItem("Selecione a avaliacao");
            for (int i = 0; i < sistema.mostraAvaliacoes().size(); i++) {
                jComboBox4.addItem(sistema.mostraAvaliacoes().get(i).getNome());
            }
            
        cadastAva.setVisible(false);
        TelaPrincipal.setVisible(true); 
        } catch (InsertException | SelectException e) {
        
        }// hides it temporarily
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            sistema.removerSemestre();

            jComboBox1.setModel(new DefaultComboBoxModel());      
            jComboBox1.addItem("Selecione o semestre");
            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
                jComboBox1.addItem(sistema.mostraSemestres().get(i).getNumSemestre());
            }
           
            }
         catch (DeleteException | SelectException e) {
            System.err.println(e);

        }
      
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
            sistema.insercaoDeNotas(Double.parseDouble(jTextField6.getText()));
            jTextPane2.setText(sistema.selecionaAvaliacao().toString());
             jTextPane3.setText(sistema.calcularNota());
        }
        catch(UpdateException | InsertException | SelectException e){

        }
            }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            // Creating a PdfDocument object
            Aluno aluno = sistema.selecionaAluno();
            String dest =  aluno.getNome().charAt(0) + ".pdf";
            PdfWriter writer;
            writer = new PdfWriter(dest);
            // Creating a PdfDocument object
            PdfDocument pdf = new PdfDocument(writer);
            // Creating a Document object
            Document doc = new Document(pdf);
            // Creating a table
            doc.add(new Paragraph("-RELATORIO DE NOTAS"));
            doc.add(new Paragraph("Aluno: " + aluno.getNome()));
            doc.add(new Paragraph("Curso: " + aluno.getCurso()));
            doc.add(new Paragraph("\n"));

            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
                // Adding cells to the table
                Semestre s = sistema.mostraSemestres().get(i);
                sistema.setIdSemestre(s.getId());
                doc.add(new Paragraph(s.toString()));

                for (int j = 0; j < sistema.mostraDisciplinas().size(); j++) {
                    Disciplina d = sistema.mostraDisciplinas().get(j);
                    sistema.setIdDisciplina(d.getId());
                    doc.add(
                            new Paragraph(d.toString()));
                    doc.add(
                            new Paragraph("" + sistema.calcularNota()));
                }

                doc.add(new Paragraph("\n"));

            }

            // Closing the document
            doc.close();
        } catch (FileNotFoundException | SelectException | InsertException e) {
            e.printStackTrace();
        
    }    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      try {
               sistema.removerDisciplina();
            }
         catch (DeleteException e) {
        }
        try {
            jComboBox3.setModel(new DefaultComboBoxModel());      
            jComboBox3.addItem("Selecione a disciplina");
            for (int i = 0; i < sistema.mostraDisciplinas().size(); i++) {
                jComboBox3.addItem(sistema.mostraDisciplinas().get(i).getNome());
            }
            jTextPane3.setText("A situacao do exame aparecera aqui depois de selecionada a disciplina com avaliacoes cadastradas");

        }
        catch(SelectException e){
    }
      
    
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        sistema.setIdAluno(-1);
        TelaPrincipal.setVisible(false);
        this.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int id = 0;

        try {
            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
                if (Objects.equals(sistema.mostraSemestres().get(i).getNumSemestre(),  jComboBox1.getSelectedItem().toString())){
                    id = sistema.mostraSemestres().get(i).getId();
                    break;}
            }

            sistema.setIdSemestre(id);

        } catch (SelectException e) {
            
        }

 try{
        jComboBox3.setModel(new DefaultComboBoxModel());      
        jComboBox3.addItem("Selecione a disciplina");
        for (int i = 0; i < sistema.mostraDisciplinas().size(); i++) {
                jComboBox3.addItem(sistema.mostraDisciplinas().get(i).getNome());
            }
        } catch (SelectException e) {

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            for (int i = 0; i < sistema.mostraDisciplinas().size(); i++) {
                if (Objects.equals(sistema.mostraDisciplinas().get(i).getNome(), jComboBox3.getSelectedItem().toString())){
                    id = sistema.mostraDisciplinas().get(i).getId();
                    break;}
            }
            sistema.setIdDisciplina(id);
        } catch (SelectException e) {

        }


        try{
            jComboBox4.setModel(new DefaultComboBoxModel());      
            jComboBox4.addItem("Selecione a avaliacao");
        for (int i = 0; i < sistema.mostraAvaliacoes().size(); i++) {
                jComboBox4.addItem(sistema.mostraAvaliacoes().get(i).getNome());
            }
        if(sistema.mostraAvaliacoes().size()!=0)
            jTextPane3.setText(sistema.calcularNota());
        else
            jTextPane3.setText("A situacao do exame aparecera aqui depois de selecionada a disciplina com avaliacoes cadastradas");
        jTextPane2.setText("A avaliacao aparecera aqui depois de selecionada");

        } catch (SelectException e) {

        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            for (int i = 0; i < sistema.mostraAvaliacoes().size(); i++) {
                if (Objects.equals(sistema.mostraAvaliacoes().get(i).getNome(), jComboBox4.getSelectedItem().toString())){
                    id = sistema.mostraAvaliacoes().get(i).getId();
                    sistema.setIdAvaliacao(id);

                    jTextPane2.setText(sistema.selecionaAvaliacao().toString());

                    break;}
            }
        } catch (SelectException | InsertException e) {

        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
               sistema.removerAvaliacao();
            }
         catch (DeleteException e) {
        }
        try {
            jComboBox4.setModel(new DefaultComboBoxModel());      
            jComboBox4.addItem("Selecione a avaliacao");
            for (int i = 0; i < sistema.mostraAvaliacoes().size(); i++) {
                jComboBox4.addItem(sistema.mostraAvaliacoes().get(i).getNome());
            
             
            }
            
            jTextPane2.setText("A avaliacao aparecera aqui depois de selecionada");
            if(sistema.mostraAvaliacoes().size()!=0)
                jTextPane3.setText(sistema.calcularNota());
            else
                jTextPane3.setText("A situacao do exame aparecera aqui depois de selecionada a disciplina com avaliacoes cadastradas");
        
        }
        catch(SelectException e){
    }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nomeSemestre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeSemestre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeSemestre2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            sistema.editarSemestre(nomeSemestre2.getText());
            jComboBox1.setModel(new DefaultComboBoxModel());      
            jComboBox1.addItem("Selecione o semestre");
            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
            jComboBox1.addItem(sistema.mostraSemestres().get(i).getNumSemestre());}
            editaSem.setVisible(false);
            TelaPrincipal.setVisible(true);
           
        } catch (UpdateException | SelectException e) {
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TelaPrincipal.setVisible(false);  
        editaSem.setVisible(true);  

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        TelaPrincipal.setVisible(false);  
        editaDis.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void nomeDisciplina3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplina3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplina3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       try {
            sistema.editarDisciplina(nomeDisciplina3.getText());
            jComboBox3.setModel(new DefaultComboBoxModel());      
            jComboBox3.addItem("Selecione a disciplina");
            for (int i = 0; i < sistema.mostraDisciplinas().size(); i++) {
            jComboBox3.addItem(sistema.mostraDisciplinas().get(i).getNome());}

            editaDis.setVisible(false);
            TelaPrincipal.setVisible(true);
           
        } catch (UpdateException | SelectException e) {
          
        } // TODO add your handling code here:
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        TelaPrincipal.setVisible(false);  
        editaAva.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 try {
            sistema.editarAvaliacao(Double.parseDouble(jTextField9.getText()), jTextField7.getText(), jTextField8.getText());
            jComboBox4.setModel(new DefaultComboBoxModel());      
            jComboBox4.addItem("Selecione a avaliacao");
            for (int i = 0; i < sistema.mostraAvaliacoes().size(); i++) {
            jComboBox4.addItem(sistema.mostraAvaliacoes().get(i).getNome());}
            jTextPane2.setText(sistema.selecionaAvaliacao().toString());
            editaAva.setVisible(false);
            TelaPrincipal.setVisible(true);
           
        } catch (UpdateException | SelectException | InsertException e) {
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        TelaCadastro.setVisible(false);// TODO add your handling code here:
        this.setVisible(true);// TODO add your handling code here:

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        TelaLogin.setVisible(false);
        this.setVisible(true); 
    }//GEN-LAST:event_jButton20ActionPerformed

    private void cpf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf1ActionPerformed
/**/
    // GEN-LAST:event_jButton3ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginActionPerformed
        this.setVisible(false); // hides it temporarily
        TelaLogin.setVisible(true); // TODO add your handling code here:
    }// GEN-LAST:event_loginActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // hides it temporarily
        TelaCadastro.setVisible(true);
    }// GEN-LAST:event_cadastroActionPerformed

    
     
    private void darLoginActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Aluno a = sistema.loginAluno(camposenha.getText(), campocpf.getText());
            if(a!=null){
                sistema.setIdAluno(a.getId());
                jComboBox1.setModel(new DefaultComboBoxModel());      
                jComboBox1.addItem("Selecione o semestre");
                for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
                jComboBox1.addItem(sistema.mostraSemestres().get(i).getNumSemestre());}
            
                TelaLogin.setVisible(false);
                TelaPrincipal.setVisible(true);}
            else{
                TelaLogin.setVisible(false); // hides it temporarily
                errologin.setVisible(true);}
     
        } catch (InsertException | SelectException e) {
         
        }
        }
    /*
    private void darLoginActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Aluno a = sistema.loginAluno(camposenha.getText(), campocpf.getText());
            sistema.setIdAluno(a.getId());

            String[] semestres = new String[20];
            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
                semestres[i] = sistema.mostraSemestres().get(i).getNumSemestre();
            }

            jList1.setModel(new DefaultComboBoxModel<>(semestres));
        } catch (InsertException | SelectException e) {
            TelaLogin.setVisible(false); // hides it temporarily
            errologin.setVisible(true);
        }
        TelaLogin.setVisible(false);
        jButton10.setVisible(false);
        jButton14.setVisible(false);

        TelaPrincipal.setVisible(true); // hides it temporarily
    }// GEN-LAST:event_darLoginActionPerformed*/

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cpfActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nomeActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarActionPerformed
        Aluno a = new Aluno();
        a.setNome(nome.getText());
        a.setSenha(senha.getText());
        a.setCpf(cpf.getText());
        a.setCurso(cpf1.getText());
        try {
            sistema.cadastrarAluno(a);
            TelaCadastro.setVisible(false);
            this.setVisible(true); // hides it temporarily
        } catch (JaCadastradoException | InsertException | SelectException e) {
           
        }
        
    }// GEN-LAST:event_cadastrarActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_senhaActionPerformed

    private void campocpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campocpfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campocpfActionPerformed

    private void okerroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okerroActionPerformed
        errologin.setVisible(false);
        TelaLogin.setVisible(true);
    }// GEN-LAST:event_okerroActionPerformed

    private void camposenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_camposenhaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_camposenhaActionPerformed

    private void CadastrarSemestreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastrarSemestreActionPerformed
        TelaPrincipal.setVisible(false);
        cadastSemes.setVisible(true);

    }// GEN-LAST:event_CadastrarSemestreActionPerformed

    private void nomeSemestreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nomeSemestreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nomeSemestreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        Semestre sem = new Semestre();
        sem.setNumSemestre(nomeSemestre.getText());
        sem.setId_aluno(sistema.getIdAluno());
        try {
            sistema.cadastrarSemestre(sem);
            jComboBox1.setModel(new DefaultComboBoxModel());      
            jComboBox1.addItem("Selecione o semestre");
            for (int i = 0; i < sistema.mostraSemestres().size(); i++) {
            jComboBox1.addItem(sistema.mostraSemestres().get(i).getNumSemestre());}
            cadastSemes.setVisible(false);
            TelaPrincipal.setVisible(true);
            
        } catch (InsertException | SelectException e) {
           
        }
         // hides it temporarily

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        ErroCadastro.setVisible(false);
        TelaCadastro.setVisible(true);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notasUDESCfinalUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notasUDESCfinalUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notasUDESCfinalUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notasUDESCfinalUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        try {
            sistema = new Sistema();
        } catch (ClassNotFoundException | SQLException | SelectException e) {
            System.err.println(e);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notasUDESCfinalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarSemestre;
    private javax.swing.JDialog ErroCadastro;
    private javax.swing.JLabel Inicio;
    private javax.swing.JFrame TelaCadastro;
    private javax.swing.JFrame TelaLogin;
    private javax.swing.JFrame TelaPrincipal;
    private javax.swing.JFrame cadastAva;
    private javax.swing.JFrame cadastDis;
    private javax.swing.JFrame cadastSemes;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cadastro;
    private javax.swing.JTextField campocpf;
    private javax.swing.JPasswordField camposenha;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField cpf1;
    private javax.swing.JButton darLogin;
    private javax.swing.JFrame editaAva;
    private javax.swing.JFrame editaDis;
    private javax.swing.JFrame editaSem;
    private javax.swing.JDialog errologin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JButton login;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeDisciplina3;
    private javax.swing.JTextField nomeSemestre;
    private javax.swing.JTextField nomeSemestre2;
    private javax.swing.JButton okerro;
    private javax.swing.JTextField senha;
    private javax.swing.JLabel titCadastro;
    // End of variables declaration//GEN-END:variables
}
